### ISSUE TITLE
support for parallel groups

### ISSUE THREAD

**Issue by robwhitby** [springernature/halfpipe#6]

**Comment by robwhitby** [comment]
new linting rules

- [ ] do not allow save + restore in same group

**Comment by stigtermichiel** [comment]
There has been some discussion internally about how to model the parallel tasks best in halfpipe. 

We chose in the end to do the non-breaking thing of having parallel parsed as a string, to remain backwards compatible. But we all agreed that a different way of modelling would be 'nicer'. This other idea is parsing it into a parallel struct:

```
type Parallel struct {
   tasks []Task
}
```

This is introducing a `task` named parallel, which job it is to run every task under it in parallel. We could start modelling this internally without exposing it to the user.

### Internal benefits:
* rendering the concourse-pipeline would be a lot easier (the current render-function is quite hard to understand)
* It models the parallelism instead of relying on strings (we are a bit naughty, by parsing yaml-bools into strings now)

We could still do this while holding backwards compatibility, by having a pre-processor that parses the halfpipe file into this `parallel` type. This way, we move some of the rendering logic into this pre-processor, making the renderer easier. We could then later decide if we want to expose this new way of modelling the halfpipe file to the user.

### Possible benefits for the user:
* I think it would be easier to understand parallelism. You get a nice indentation of all parallel tasks that belong to each other
* no chance of mistyping groups etc.

 ### Downsides for the user:
* If we decide to remove the _old_ way of parallelising tasks, users are forced to change their pipelines (currently 150 pipelines use this way)

**Comment by robwhitby** [comment]
yeah sounds good. Could break it down like this..

1. refactor to model parallel better

then optionally:

2. support it in halfpipe manifest

```yaml
tasks:
- type: run
- type: parallel
  tasks:
  - type: run
  - type: docker-compose
- type: deploy-cf
```

3. Remove support for old `parallel: <string>` on tasks

4: introduce `seq` so you can build really crazy pipelines :D
